"""Regenerate `prereg/CATALOG.md` from the directory itself.

`prereg/` is the registration bundle: 104 files whose names are the only clue to which study each one
governs. The catalogue is the navigational index over them. It used to claim it was "generated from
the directory" while in fact being hand-written, so it could drift silently — which is the failure the
index exists to prevent. This script makes the claim true.

    python scripts/build_prereg_catalog.py            # rewrite prereg/CATALOG.md
    python scripts/build_prereg_catalog.py --check    # exit 1 if it is stale (used by the test suite)

Study membership is derived from the on-disk folder, so adding a registration to
`prereg/studies/<slug>/` is all that is needed for it to appear here.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
PREREG = ROOT / "prereg"
CATALOG = PREREG / "CATALOG.md"

# slug -> (title, which paper it serves, OSF registration ids)
STUDIES: dict[str, tuple[str, str, tuple[str, ...]]] = {
    "deep_case_spb": ("San Pedro Bay deep case (parent)", "Paper D", ()),
    "route_a": (
        "Route-A computational silver labels",
        "Paper C (isolated)",
        ("3kd6m", "6pqyc", "9wrzh", "udq5m"),
    ),
    "operational_records": (
        "Operational-record state validation",
        "Paper C study 1",
        ("vwd9k",),
    ),
    "g1_v2": ("G1-v2 successor protocol", "future work", ()),
    "spb_queue_boundary": (
        "SPB queue-boundary direct measurement and reanalysis",
        "Papers C study 2, D",
        ("5sc3v",),
    ),
    "spb_labour": (
        "SPB 2014-15 labour spatial replication",
        "Paper D context",
        ("mbu46", "x96np"),
    ),
    "spb_emissions": ("SPB freight-OGV emissions component", "Paper D", ("p5vqs",)),
    "spb_atberth": ("CARB At-Berth SPB tanker extension", "Paper D", ("w6zsg",)),
    "spb_ab617": ("AB 617 source-oriented air quality", "Paper D", ("j6utx",)),
    "baltimore": (
        "Baltimore infrastructure shock",
        "Paper C study 3",
        ("dxy94", "rpj42", "uzxcv"),
    ),
    "nature_recovery": (
        "Nature-recovery R-G1 tanker arrival gate",
        "Paper C study 4",
        ("2sd9u", "jh3ea"),
    ),
}

SECTIONS = {
    "protocol": "Cross-cutting registered design — applies to every study",
    "governance": "Locks, registries and OSF identity",
}


def _listing(directory: Path) -> list[str]:
    return sorted(p.name for p in directory.iterdir() if p.is_file())


def _osf(ids: tuple[str, ...]) -> str:
    if not ids:
        return "—"
    return ", ".join(f"[{i}](https://osf.io/{i}/)" for i in ids)


def render() -> str:
    studies_root = PREREG / "studies"
    on_disk = sorted(p.name for p in studies_root.iterdir() if p.is_dir())
    unknown = [s for s in on_disk if s not in STUDIES]
    if unknown:
        raise SystemExit(
            f"study folder(s) with no entry in STUDIES: {unknown}\n"
            f"add them to {Path(__file__).name} so they appear in the catalogue"
        )

    total = sum(1 for p in PREREG.rglob("*") if p.is_file())
    out: list[str] = []
    add = out.append

    add("# `prereg/` catalogue — what each registration governs")
    add("")
    add("Generated by `scripts/build_prereg_catalog.py` from the directory itself — do not hand-edit.")
    add("Regenerate after adding a registration; `tests/test_prereg_catalog.py` fails if it is stale.")
    add("")
    add(f"{total} files. Layout and the rules for changing it are in `README.md`.")
    add("")
    add("| Study | Paper | Files | OSF registrations |")
    add("|---|---|---:|---|")
    for slug in on_disk:
        title, paper, ids = STUDIES[slug]
        n = len(_listing(studies_root / slug))
        add(f"| [{title}](studies/{slug}/) | {paper} | {n} | {_osf(ids)} |")
    for name, title in SECTIONS.items():
        n = len(_listing(PREREG / name))
        add(f"| [{title}]({name}/) | all | {n} | — |")
    n_amend = len(_listing(PREREG / "amendments"))
    add(f"| [Amendments — the only way to change anything registered](amendments/) | all | {n_amend} | — |")
    add("")

    for name, title in SECTIONS.items():
        add(f"## `{name}/` — {title}")
        add("")
        for f in _listing(PREREG / name):
            add(f"- `{name}/{f}`")
        add("")

    add("## `studies/` — one folder per registered study")
    add("")
    for slug in on_disk:
        title, paper, ids = STUDIES[slug]
        add(f"### `studies/{slug}/` — {title} ({paper})")
        add("")
        if ids:
            add(f"OSF: {_osf(ids)}")
            add("")
        for f in _listing(studies_root / slug):
            add(f"- `studies/{slug}/{f}`")
        add("")

    add("## `amendments/` — dated changes to the registered record")
    add("")
    for f in _listing(PREREG / "amendments"):
        add(f"- `amendments/{f}`")
    add("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the catalogue is stale")
    args = parser.parse_args()

    wanted = render()
    if args.check:
        current = CATALOG.read_text(encoding="utf-8") if CATALOG.is_file() else ""
        if current != wanted:
            print("prereg/CATALOG.md is stale — run: python scripts/build_prereg_catalog.py")
            return 1
        print("prereg/CATALOG.md is current")
        return 0

    CATALOG.write_text(wanted, encoding="utf-8", newline="")
    print(f"wrote {CATALOG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
